# Generated by Django 2.0 on 2019-07-13 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0005_auto_20190713_1150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='section',
        ),
        migrations.AddField(
            model_name='exam',
            name='section',
            field=models.ManyToManyField(to='exam.Section'),
        ),
    ]
