# Generated by Django 2.0 on 2019-07-13 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0006_auto_20190713_1154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='no_of_question',
        ),
    ]
